### PR TITLE
[feat]  Subdomain for my college project

### PR DESCRIPTION
**Pull request by LoriaLawrenceZ**
My project is called dex, its an prototype of an (fake) ai chat that solves n1 and n2 support. It is a college mandatory project

### 🌐 Website

**Link:** 

[Mercury DEX](https://mercury-mocha-chi.vercel.app/)

**Screenshot:** 

image

### 📋 Checklist

- [x] I have starred the repository.
- [x] I have read and accepted the [Terms of Service](/Terms-of-Service.md).
- [x] There is reasonable content on my site.
- [x] I have configured a custom domain for my site.

### CODE REVIEW

**Comment by katorly** [comment]
Welcome! Please complete the following steps to make the subdomain work:
1. Add the custom domain to your Vercel project:
image
2. Paste the TXT record value needed to be added here:
image

**Comment by LoriaLawrenceZ** [comment]
image

**Comment by katorly** [comment]
Waiting for Vercel to recognize the domain records... This may take up to 24 hours. Please don't remove the custom domain added to your project.

**Comment by LoriaLawrenceZ** [comment]
It seems to be already working, do i need to do something more here or in vercel?
If not, i'm really thankful for what you are doing, i already starred the repository and sent it to my dev friends.
Keep the good work!

**Comment by katorly** [comment]
Your site is live at [dex.rweb.site](https://dex.rweb.site) 🎉

**Comment by katorly** [comment]
> It seems to be already working, do i need to do something more here or in vercel?
> 
> image
> 
> If not, i'm really thankful for what you are doing, i already starred the repository and sent it to my dev friends. Keep the good work!

It's working, I just forgot that the project owner have to open the custom domain page in Vercel again to make it work after adding domain records 😂

**Pull request merged**
