### PR TITLE
Update records.json

### PR DESCRIPTION
**Pull request by amuybar**
Please go the the `Preview` tab and select your preferred language | 请点击上方的 `Preview` 并选择你的语言

* [English](?expand=1&template=pull_request_template.en-US.md)
* [简体中文](?expand=1&template=pull_request_template.zh-CN.md)

### CODE REVIEW

**Comment by katorly** [comment]
Welcome! We have pointed a CNAME record to your website, however, the website [softwares.rweb.site](http://softwares.rweb.site) is returning 404 error code.

Have you set a custom domain in your vercel project?

**Comment by amuybar** [comment]
let me check on that

**Comment by katorly** [comment]
We still cannot reach the site. Have you check your `https://vercel.com/yourname/yourproject/settings/domains`? It suppose to be like this:  

image

**Comment by amuybar** [comment]
It's exactly like that .

**Comment by katorly** [comment]
Is vercel custom domain settings showing this message? If yes, please provide the TXT record name and value that needs to be verified.

image

**Comment by amuybar** [comment]
> Is vercel custom domain settings showing this message? If yes, please provide the TXT record name and value that needs to be verified.
> 
> image

Am not seeing that

**Comment by amuybar** [comment]
[image: Screenshot from 2024-05-24 13-53-28.png]

**Comment by amuybar** [comment]
Screenshot from 2024-05-24 14-03-34

**Comment by katorly** [comment]
Unfortunately we are still unable to reach your site. May I ask you to please delete that custom domain in your vercel panel and re-assign one, and send me the TXT records that needs to be added?

image

image

**Comment by katorly** [comment]
Well, it is working, congrats.

Your site is live at [softwares.rweb.site](https://softwares.rweb.site) 🎉

**Pull request merged**
