### PR TITLE
Update records.json

### PR DESCRIPTION
**Pull request by aryannn053**
### 🌐 Website
Link: aryxnn.vercel.app (Portfolio)
aryan.rweb.site (To be registered)

**Screenshot:** 

image

### 📋 Checklist

- [x] I have starred the repository.
- [x] I have read and accepted the [Terms of Service](/Terms-of-Service.md).
- [x] There is reasonable content on my site.
- [x] I have configured a custom domain for my site

### CODE REVIEW

**Comment by katorly** [comment]
Welcome! In order to make the subdomain available for your Vercel website, please complete the following instructions:
1. Add the custom domain qincai.rweb.site to your Vercel project:
image
2. Show me, or copy-paste me the value of the TXT record needed to verify domain ownership:
image

**Comment by aryannn053** [comment]
image

**Comment by katorly** [comment]
We have added the record for you 20 minutes ago and Vercel is still returning a 404 error code.  
I will check again in 24 hours to see if it still returns a 404. Let me know if [aryan.rweb.site](http://aryan.rweb.site) no longer returns a 404 on your end.

**Comment by aryannn053** [comment]
Alright! It returns 404 on my side too!

**Comment by katorly** [comment]
> Alright! It returns 404 on my side too!

Did you delete the custom domain in your Vercel project?

Would you mind showing me a screenshot of this page of your project?

image

**Comment by aryannn053** [comment]
It works fine here! I just had to open the domains page in my vercel page.
image

**Comment by katorly** [comment]
Your site is live at [aryan.rweb.site](https://aryan.rweb.site) 🎉

By the way, your website looks amazing! It's clean and neat.

**Pull request merged**
