### PR TITLE
Update records.json

### PR DESCRIPTION
**Pull request by bananaking6**
### 🌐 Website

Link: skibidi-neon.vercel.app
go.rweb.site

**Screenshot:**
image

### 📋 Checklist

- [x] I have starred the repository.
- [x] I have read and accepted the [Terms of Service](/Terms-of-Service.md).
- [x] There is reasonable content on my site.
- [x] I have configured a custom domain for my site.

### CODE REVIEW

**Comment by katorly** [comment]
Welcome! In order to make the subdomain available for your Vercel website, please complete the following instructions:

1. Add the custom domain to your Vercel project:
image
2. Copy-paste me the value of the TXT record needed to verify domain ownership:
image

**Comment by bananaking6** [comment]
vc-domain-verify=go.rweb.site,7a6529cb449031c64faa

**Comment by katorly** [comment]
We have added the record. Please open this page once again:
image

**Comment by bananaking6** [comment]
Alright it works

**Comment by katorly** [comment]
Your site is live at [go.rweb.site](https://go.rweb.site) 🎉

**Comment by katorly** [comment]
Hi @bananaking6 ,

We noticed that the website linked to your subdomain is currently not accessible.

Please reply here or restore your website within **2 months** if you'd like to keep the subdomain. If we don't hear back from you by then, we'll assume it's no longer needed and may revoke it.

If this is a mistake or you need more time, just reply to let us know.

Thanks 🙂

**Pull request merged**
