### PR TITLE
Update records.json

### PR DESCRIPTION
**Pull request by revvnik**
### 🌐 Link

**Link:** 

https://revvnik.github.io/portfolio

### 📋 Checklist

- [x] I have starred the repository.
- [x] I have read and accepted the [Terms of Service](/Terms-of-Service.md).
- [x] There is reasonable content on my site.
- [x] I have configured a custom domain for my site.

### CODE REVIEW

**Comment by katorly** [comment]
I have added a CNAME record for you. However, may I ask you to go to your repo https://github.com/revvnik/portfolio, click "Settings", click "Pages", and input "revvnik.rweb.site" at the "Custom domain" section to make Github recognize the CNAME:

image

**Comment by katorly** [comment]
I apologize for the inconvenience, but in your [commit](https://github.com/revvnik/portfolio/commit/ffaa2a2c6976cd9eabfbf96b3aa691ea556ee88c), you deleted the CNAME file generated by Github. That's a file for Github Pages to verify whether the CNAME record pointed to your site was with your consent, so you need to keep that file to make the custom domain work.

**Comment by revvnik** [comment]
Wonderful, thank you very much!

**Comment by revvnik** [comment]
> I apologize for the inconvenience, but in your [commit](https://github.com/revvnik/portfolio/commit/ffaa2a2c6976cd9eabfbf96b3aa691ea556ee88c), you deleted the CNAME file generated by Github. That's a file for Github Pages to verify whether the CNAME record pointed to your site was with your consent, so you need to keep that file to make the custom domain work.

Ooh right my bad, thanks for pointing it out!

**Comment by katorly** [comment]
Your site is live at [revvnik.rweb.site](https://revvnik.rweb.site/) 🎉

**Comment by katorly** [comment]
@revvnik 

Hello! We noticed you removed this subdomain from your site. GitHub Pages doesn't support multiple domains pointing to the same website, so visiting your subdomain now will return a 404 error.

Do you still need the subdomain?

**Comment by katorly** [comment]
Your subdomain has been removed due to:
> The applicant @revvnik removed the subdomain from their GitHub Pages.

You are always welcome to request subdomains again by opening new applications.

For more details, see #68

**Pull request merged**
