### PR TITLE
Update records.json

### PR DESCRIPTION
**Pull request by raselshikdar**
### 🌐 Website

**Link:** 

**Screenshot:** 

### 📋 Checklist

- [x] I have starred the repository.
- [x] I have read and accepted the [Terms of Service](/Terms-of-Service.md).
- [x] There is reasonable content on my site.
- [x] I have configured a custom domain for my site.

### CODE REVIEW

**Comment by katorly** [comment]
Hi! You are updating your previous subdomain record.

Please complete Step 4 and Step 5 in https://github.com/katorlys/rweb.site/wiki/Vercel to make Vercel recognize the DNS record.

**Comment by raselshikdar** [comment]
vc-domain-verify=devlog.rweb.site,1246de14ba871c5e7b53

**Comment by katorly** [comment]
Now please complete Step 6 in https://github.com/katorlys/rweb.site/wiki/Vercel and then you can access your site from the subdomain.

**Comment by raselshikdar** [comment]
Done ✅ 
Thanks a lot ❤️

**Pull request merged**
